# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuestos', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('uuid', models.CharField(blank=True, max_length=48, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('folio', models.CharField(blank=True, default='00', max_length=100, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'facturas',
                'ordering': ['id'],
                'verbose_name': 'factura',
            },
        ),
        migrations.CreateModel(
            name='InfoFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Emisor', 'Emisor'), ('Receptor', 'Receptor')], max_length=32)),
                ('nombre', models.CharField(blank=True, max_length=512, null=True)),
                ('rfc', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=1024, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=512, null=True)),
                ('noexterior', models.CharField(blank=True, max_length=32, null=True)),
                ('nointerior', models.CharField(blank=True, max_length=32, null=True)),
                ('colonia', models.CharField(blank=True, max_length=512, null=True)),
                ('municipio', models.CharField(blank=True, max_length=512, null=True)),
                ('localidad', models.CharField(blank=True, max_length=512, null=True)),
                ('estado', models.CharField(blank=True, max_length=512, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'informaciones Fiscales',
                'ordering': ['id'],
                'verbose_name': 'informacion Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=1024, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('tipo', models.CharField(blank=True, max_length=128, null=True)),
                ('impuesto', models.CharField(blank=True, max_length=4, null=True)),
                ('factor', models.DecimalField(decimal_places=2, default=0.16, max_digits=19)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'conceptos',
                'ordering': ['id'],
                'verbose_name': 'concepto',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.ManyToManyField(blank=True, to='api.Servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='personas',
            field=models.ManyToManyField(blank=True, to='api.InfoFiscal'),
        ),
        migrations.AddField(
            model_name='factura',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
